version: '2'
services:
  web:
    build: ./webapp
    image: data_plane:0.1-alpha
    ports: 
      - "8080:9000"
    links:
      - dp_db_init
      - dp_db

  dp_db_init:
    build: ./dp-setup
    volumes:
      - ./dp-setup/:/code
    links:
      - dp_db
    command: python dbinit.py

  dp_db:
    image: mongo
