{{ if .Values.knox.certPem }}
#
# Secret spec for certificates
#
apiVersion: v1
kind: Secret
metadata:
  name: dp-certs-secret-{{ .Release.Name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ template "projectName" . }}
    version: {{ .Chart.Version }}
    dpVersion: {{ .Values.global.dpVersion }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  ssl-cert.pem: {{ .Values.knox.certPem | b64enc | quote }}
  ssl-key.pem: {{ .Values.knox.certPrivateKeyPem | b64enc | quote }}
{{ end }}