apiVersion: v1
kind: Service
metadata:
  name: {{ template "projectName" . }}-{{.Release.Name}}-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ template "projectName" . }}
    version: {{ .Chart.Version }}
    dpVersion: {{ .Values.global.dpVersion }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ template "projectName" . }}
    release: {{ .Release.Name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
    - name: http-knox
      protocol: TCP
      port: {{ .Values.service.externalSSLPort }}
      targetPort: {{ .Values.service.internalSSLPort }}