/*
 * HORTONWORKS DATAPLANE SERVICE AND ITS CONSTITUENT SERVICES
 *
 * (c) 2016-2018 Hortonworks, Inc. All rights reserved.
 *
 * This code is provided to you pursuant to your written agreement with Hortonworks, which may be the terms
 * of the Affero General Public License version 3 (AGPLv3), or pursuant to a written agreement with a third party
 * authorized to distribute this code.  If you do not have a written agreement with Hortonworks or with
 * an authorized and properly licensed third party, you do not have any rights to this code.
 *
 * If this code is provided to you under the terms of the AGPLv3: A) HORTONWORKS PROVIDES THIS CODE TO YOU
 * WITHOUT WARRANTIES OF ANY KIND; (B) HORTONWORKS DISCLAIMS ANY AND ALL EXPRESS AND IMPLIED WARRANTIES WITH
 * RESPECT TO THIS CODE, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE; (C) HORTONWORKS IS NOT LIABLE TO YOU, AND WILL NOT DEFEND, INDEMNIFY,
 * OR HOLD YOU HARMLESS FOR ANY CLAIMS ARISING FROM OR RELATED TO THE CODE; AND (D) WITH RESPECT
 * TO YOUR EXERCISE OF ANY RIGHTS GRANTED TO YOU FOR THE CODE, HORTONWORKS IS NOT LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, PUNITIVE OR CONSEQUENTIAL DAMAGES INCLUDING, BUT NOT LIMITED TO,
 * DAMAGES RELATED TO LOST REVENUE, LOST PROFITS, LOSS OF INCOME, LOSS OF BUSINESS ADVANTAGE OR UNAVAILABILITY,
 * OR LOSS OR CORRUPTION OF DATA.
 */

export const POLICY_EDIT = 'policy_edit';
export const REPLICATION_WASB_SUPPORT = 'wasbReplicationSupported';
export const REPLICATION_ABFS_SUPPORT = 'replication_abfs_support';
export const REPLICATION_ADLS_SUPPORT = 'replication_adls_support';
export const CLUSTER_SYNC_SUPPORT = 'clusterUpdateSupported';
export const POLICY_SNAPSHOTABLE_EDIT = 'enableSnapshotBasedReplication';
export const HDFS_FILTER = 'fileListingFilterEnabled';
export const REPLICATION_GCS_SUPPORT = 'gcsReplicationSupported';

export const FEATURES = {
  [POLICY_EDIT]: POLICY_EDIT,
  [REPLICATION_WASB_SUPPORT]: REPLICATION_WASB_SUPPORT,
  [REPLICATION_ABFS_SUPPORT]: REPLICATION_ABFS_SUPPORT,
  [REPLICATION_ADLS_SUPPORT]: REPLICATION_ADLS_SUPPORT,
  [CLUSTER_SYNC_SUPPORT]: CLUSTER_SYNC_SUPPORT,
  [POLICY_SNAPSHOTABLE_EDIT]: POLICY_SNAPSHOTABLE_EDIT,
  [HDFS_FILTER]: HDFS_FILTER,
  [REPLICATION_GCS_SUPPORT]: REPLICATION_GCS_SUPPORT,
};
