export const SUPERADMIN = 'SUPERADMIN';
export const INFRAADMIN = 'INFRAADMIN';
export const CURATOR = 'CURATOR';
export const INFRAADMIN_SUPERADMIN = 'INFRAADMIN_SUPERADMIN';
export const USER = 'USER';

export const ROLES = {
  SUPERADMIN: SUPERADMIN,
  INFRAADMIN: INFRAADMIN,
  CURATOR: CURATOR,
  INFRAADMIN_SUPERADMIN: INFRAADMIN_SUPERADMIN,
  USER: USER
};
