version: '2'
services:
  knox:
    image: hortonworks/dp-knox
    ports:
    - "8443:8443"
    environment:
     - MASTER_PASSWORD
     - USE_TEST_LDAP
     - CONSUL_HOST
    command: sh ./launch-knox.sh
