version: '2'
services:
  dp-database:
    image: postgres
    environment:
        POSTGRES_PASSWORD: dp_admin
        POSTGRES_USER: dp_admin
        POSTGRES_DB: dataplane
  dp-db-service:
    image: hortonworks/dp-db-service
    ports:
        - "9000:9000"
    depends_on:
        - dp-database
    links:
        - dp-database
  dp-cluster-service:
    image: hortonworks/dp-cluster-service
    ports:
        - "9009:9009"
    depends_on:
        - dp-database
    links:
        - dp-database
  dp-app:
    image: hortonworks/dp-app
    ports:
        - "80:80"
    volumes:
        - ./certs:/usr/dp-app/conf/cert
    environment:
        DP_APP_HOME: "/usr/dp-app"
    depends_on:
        - dp-cluster-service
        - dp-db-service
        - dp-database
    links:
        - dp-cluster-service
        - dp-db-service
        - dp-database
