version: '2'  
services:
  dp-consul-server:
    image: consul
    network_mode: "host"
    command: agent -server -bootstrap -bind=${CONSUL_HOST} -client=${CONSUL_HOST} -ui
  dp-gateway:
    image: hortonworks/dp-gateway
    ports:
      - "8762:8762"
    environment:
      CONSUL_HOST: ${CONSUL_HOST}
  dp-database:
     image: postgres
     environment:
        POSTGRES_PASSWORD: dp_admin
        POSTGRES_USER: dp_admin
        POSTGRES_DB: dataplane
        CONSUL_HOST: ${CONSUL_HOST}
  dp-db-service:
    image: hortonworks/dp-db-service
    ports:
        - "9000:9000"
    depends_on:
        - dp-database
    links:
        - dp-database
    environment:
      CONSUL_HOST: ${CONSUL_HOST}
  dp-cluster-service:
    image: hortonworks/dp-cluster-service
    ports:
        - "9009:9009"
    depends_on:
        - dp-database
    links:
        - dp-database
    environment:
      CONSUL_HOST: ${CONSUL_HOST}
  dp-app:
    image: hortonworks/dp-app
    ports:
        - "80:80"
        - "8080:9000"
    volumes:
        - ./certs:/usr/dp-app/conf/cert
    environment:
        DP_APP_HOME: "/usr/dp-app"
        CONSUL_HOST: ${CONSUL_HOST}
    depends_on:
        - dp-cluster-service
        - dp-db-service
        - dp-database
    links:
        - dp-cluster-service
        - dp-db-service
        - dp-database
