version: '2'  
services:
  dp-gateway:
    image: hortonworks/dp-gateway
    ports:
      - "8762:8762"
    volumes:
      - ./certs:/usr/dp-app/conf/cert
    environment:
      CONSUL_HOST: ${CONSUL_HOST}
    command: --knox.url=https://${KNOX_FQDN}:8443
  dp-database:
     image: postgres
     environment:
        POSTGRES_PASSWORD: dp_admin
        POSTGRES_USER: dp_admin
        POSTGRES_DB: dataplane
        CONSUL_HOST: ${CONSUL_HOST}
  dp-db-service:
    image: hortonworks/dp-db-service
    depends_on:
        - dp-database
    links:
        - dp-database
    environment:
      CONSUL_HOST: ${CONSUL_HOST}
  dp-cluster-service:
    image: hortonworks/dp-cluster-service
    depends_on:
        - dp-database
    links:
        - dp-database
    environment:
      CONSUL_HOST: ${CONSUL_HOST}
  dp-app:
    image: hortonworks/dp-app
    ports:
        - "80:80"
    volumes:
        - ./certs:/usr/dp-app/conf/cert
    environment:
        DP_APP_HOME: "/usr/dp-app"
        CONSUL_HOST: ${CONSUL_HOST}
    depends_on:
        - dp-cluster-service
        - dp-db-service
        - dp-database
    links:
        - dp-cluster-service
        - dp-db-service
        - dp-database
