export class TypeDefs {
  entityDefs: any[] = [];
  
  static getData(): any {
    return {
      'enumDefs': [],
      'structDefs': [],
      'classificationDefs': [],
      'entityDefs': [
        {
        'category': 'ENTITY',
        'guid': '2f69f138-16fe-4466-9fca-dd9222ba2c9d',
        'createTime': 1494492733345,
        'updateTime': 1494492733345,
        'version': 1,
        'name': 'falcon_feed_replication',
        'description': 'falcon_feed_replication',
        'typeVersion': '1.0',
        'attributeDefs': [],
        'superTypes': ['Process']
      }, {
        'category': 'ENTITY',
        'guid': 'f8efbc43-70a7-46f5-8e7c-a5e85304badc',
        'createTime': 1494492733415,
        'updateTime': 1494492733415,
        'version': 1,
        'name': 'falcon_process',
        'description': 'falcon_process',
        'typeVersion': '1.0',
        'attributeDefs': [{
          'name': 'frequency',
          'typeName': 'string',
          'isOptional': false,
          'cardinality': 'SINGLE',
          'valuesMinCount': 1,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }, {
          'name': 'runs-on',
          'typeName': 'falcon_cluster',
          'isOptional': false,
          'cardinality': 'SINGLE',
          'valuesMinCount': 1,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': true
        }, {
          'name': 'tags',
          'typeName': 'map<string,string>',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }, {
          'name': 'pipelines',
          'typeName': 'string',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': true
        }, {
          'name': 'workflow-properties',
          'typeName': 'map<string,string>',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }],
        'superTypes': ['Process']
      }, {
        'category': 'ENTITY',
        'guid': '5e5b6cce-5114-4d52-871a-03e4ddb32f9c',
        'createTime': 1494492733448,
        'updateTime': 1494492733448,
        'version': 1,
        'name': 'falcon_feed_creation',
        'description': 'falcon_feed_creation',
        'typeVersion': '1.0',
        'attributeDefs': [{
          'name': 'stored-in',
          'typeName': 'falcon_cluster',
          'isOptional': false,
          'cardinality': 'SINGLE',
          'valuesMinCount': 1,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': true
        }],
        'superTypes': ['Process']
      }, {
        'category': 'ENTITY',
        'guid': 'ef12151f-f5f1-42d1-9523-a1cd649291d0',
        'createTime': 1494492721746,
        'updateTime': 1494492721746,
        'version': 1,
        'name': 'DataSet',
        'description': 'DataSet',
        'typeVersion': '1.0',
        'attributeDefs': [],
        'superTypes': ['Referenceable', 'Asset']
      }, {
        'category': 'ENTITY',
        'guid': 'd49d27d2-8264-409e-8714-26f081e70780',
        'createTime': 1494492723178,
        'updateTime': 1494492723178,
        'version': 1,
        'name': 'Process',
        'description': 'Process',
        'typeVersion': '1.0',
        'attributeDefs': [{
          'name': 'inputs',
          'typeName': 'array<DataSet>',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }, {
          'name': 'outputs',
          'typeName': 'array<DataSet>',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }],
        'superTypes': ['Referenceable', 'Asset']
      }, {
        'category': 'ENTITY',
        'guid': '075a2907-8abd-48fa-a0b3-9393e8dca4db',
        'createTime': 1494492730261,
        'updateTime': 1494492739626,
        'version': 2,
        'name': 'hive_table',
        'description': 'hive_table',
        'typeVersion': '1.2',
        'options': {'schemaElementsAttribute': 'columns'},
        'attributeDefs': [{
          'name': 'db',
          'typeName': 'hive_db',
          'isOptional': false,
          'cardinality': 'SINGLE',
          'valuesMinCount': 1,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }, {
          'name': 'createTime',
          'typeName': 'date',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }, {
          'name': 'lastAccessTime',
          'typeName': 'date',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }, {
          'name': 'comment',
          'typeName': 'string',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }, {
          'name': 'retention',
          'typeName': 'int',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }, {
          'name': 'sd',
          'typeName': 'hive_storagedesc',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false,
          'constraints': [{'type': 'ownedRef'}]
        }, {
          'name': 'partitionKeys',
          'typeName': 'array<hive_column>',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false,
          'constraints': [{'type': 'ownedRef'}]
        }, {
          'name': 'aliases',
          'typeName': 'array<string>',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }, {
          'name': 'columns',
          'typeName': 'array<hive_column>',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false,
          'constraints': [{'type': 'ownedRef'}]
        }, {
          'name': 'parameters',
          'typeName': 'map<string,string>',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }, {
          'name': 'viewOriginalText',
          'typeName': 'string',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }, {
          'name': 'viewExpandedText',
          'typeName': 'string',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }, {
          'name': 'tableType',
          'typeName': 'string',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }, {
          'name': 'temporary',
          'typeName': 'boolean',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': true
        }, {
          'name': 'profileData',
          'typeName': 'hive_table_profile_data',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': -1,
          'valuesMaxCount': -1,
          'isUnique': false,
          'isIndexable': false
        }],
        'superTypes': ['DataSet']
      }, {
        'category': 'ENTITY',
        'guid': '61a86ef6-cdae-4b74-a725-6bbf32c5623d',
        'createTime': 1494492730615,
        'updateTime': 1494492730615,
        'version': 1,
        'name': 'hive_db',
        'description': 'hive_db',
        'typeVersion': '1.0',
        'attributeDefs': [{
          'name': 'clusterName',
          'typeName': 'string',
          'isOptional': false,
          'cardinality': 'SINGLE',
          'valuesMinCount': 1,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': true
        }, {
          'name': 'location',
          'typeName': 'string',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }, {
          'name': 'parameters',
          'typeName': 'map<string,string>',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }, {
          'name': 'ownerType',
          'typeName': 'hive_principal_type',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }],
        'superTypes': ['Referenceable', 'Asset']
      }, {
        'category': 'ENTITY',
        'guid': '94040cc1-b0eb-4f90-9e1b-cc9c5a28cc47',
        'createTime': 1494492732694,
        'updateTime': 1494492732694,
        'version': 1,
        'name': 'sqoop_dbdatastore',
        'description': 'sqoop_dbdatastore',
        'typeVersion': '1.0',
        'attributeDefs': [{
          'name': 'dbStoreType',
          'typeName': 'string',
          'isOptional': false,
          'cardinality': 'SINGLE',
          'valuesMinCount': 1,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': true
        }, {
          'name': 'storeUse',
          'typeName': 'string',
          'isOptional': false,
          'cardinality': 'SINGLE',
          'valuesMinCount': 1,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }, {
          'name': 'storeUri',
          'typeName': 'string',
          'isOptional': false,
          'cardinality': 'SINGLE',
          'valuesMinCount': 1,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }, {
          'name': 'source',
          'typeName': 'string',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': true
        }],
        'superTypes': ['DataSet']
      }, {
        'category': 'ENTITY',
        'guid': '95797469-479d-4323-9665-293192daab90',
        'createTime': 1494492737214,
        'updateTime': 1494492737214,
        'version': 1,
        'name': 'storm_node',
        'description': 'storm_node',
        'typeVersion': '1.0',
        'attributeDefs': [{
          'name': 'name',
          'typeName': 'string',
          'isOptional': false,
          'cardinality': 'SINGLE',
          'valuesMinCount': 1,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': true
        }, {
          'name': 'description',
          'typeName': 'string',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': true
        }, {
          'name': 'driverClass',
          'typeName': 'string',
          'isOptional': false,
          'cardinality': 'SINGLE',
          'valuesMinCount': 1,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': true
        }, {
          'name': 'conf',
          'typeName': 'map<string,string>',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }],
        'superTypes': []
      }, {
        'category': 'ENTITY',
        'guid': 'e970662c-e63c-4650-ab9a-8f91310d9fec',
        'createTime': 1494492730092,
        'updateTime': 1494492730092,
        'version': 1,
        'name': 'hive_process',
        'description': 'hive_process',
        'typeVersion': '1.0',
        'attributeDefs': [{
          'name': 'startTime',
          'typeName': 'date',
          'isOptional': false,
          'cardinality': 'SINGLE',
          'valuesMinCount': 1,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }, {
          'name': 'endTime',
          'typeName': 'date',
          'isOptional': false,
          'cardinality': 'SINGLE',
          'valuesMinCount': 1,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }, {
          'name': 'userName',
          'typeName': 'string',
          'isOptional': false,
          'cardinality': 'SINGLE',
          'valuesMinCount': 1,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': true
        }, {
          'name': 'operationType',
          'typeName': 'string',
          'isOptional': false,
          'cardinality': 'SINGLE',
          'valuesMinCount': 1,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': true
        }, {
          'name': 'queryText',
          'typeName': 'string',
          'isOptional': false,
          'cardinality': 'SINGLE',
          'valuesMinCount': 1,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }, {
          'name': 'queryPlan',
          'typeName': 'string',
          'isOptional': false,
          'cardinality': 'SINGLE',
          'valuesMinCount': 1,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }, {
          'name': 'queryId',
          'typeName': 'string',
          'isOptional': false,
          'cardinality': 'SINGLE',
          'valuesMinCount': 1,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }, {
          'name': 'recentQueries',
          'typeName': 'array<string>',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }, {
          'name': 'clusterName',
          'typeName': 'string',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }, {
          'name': 'queryGraph',
          'typeName': 'string',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }],
        'superTypes': ['Process']
      }, {
        'category': 'ENTITY',
        'guid': '05310b47-71ab-4d6a-8980-4fe135cc8a9c',
        'createTime': 1494492734348,
        'updateTime': 1494492734348,
        'version': 1,
        'name': 'hbase_column',
        'description': 'hbase_column',
        'typeVersion': '1.0',
        'attributeDefs': [{
          'name': 'column_family',
          'typeName': 'hbase_column_family',
          'isOptional': false,
          'cardinality': 'SINGLE',
          'valuesMinCount': 1,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false,
          'constraints': [{'type': 'inverseRef', 'params': {'attribute': 'columns'}}]
        }],
        'superTypes': ['DataSet']
      }, {
        'category': 'ENTITY',
        'guid': 'f01b3cd9-7d96-45f7-959f-95a18d856ac5',
        'createTime': 1494492719898,
        'updateTime': 1494492719898,
        'version': 1,
        'name': 'Referenceable',
        'description': 'Referenceable',
        'typeVersion': '1.0',
        'attributeDefs': [{
          'name': 'qualifiedName',
          'typeName': 'string',
          'isOptional': false,
          'cardinality': 'SINGLE',
          'valuesMinCount': 1,
          'valuesMaxCount': 1,
          'isUnique': true,
          'isIndexable': true
        }],
        'superTypes': []
      }, {
        'category': 'ENTITY',
        'guid': 'adf55048-7854-41b3-8fab-92720995334e',
        'createTime': 1494492736200,
        'updateTime': 1494492736200,
        'version': 1,
        'name': 'jms_topic',
        'description': 'jms_topic',
        'typeVersion': '1.0',
        'attributeDefs': [{
          'name': 'topic',
          'typeName': 'string',
          'isOptional': false,
          'cardinality': 'SINGLE',
          'valuesMinCount': 1,
          'valuesMaxCount': 1,
          'isUnique': true,
          'isIndexable': true
        }, {
          'name': 'uri',
          'typeName': 'string',
          'isOptional': false,
          'cardinality': 'SINGLE',
          'valuesMinCount': 1,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }],
        'superTypes': ['DataSet']
      }, {
        'category': 'ENTITY',
        'guid': '527c47dd-be59-480e-91fd-03e53d425975',
        'createTime': 1494492733381,
        'updateTime': 1494492733381,
        'version': 1,
        'name': 'falcon_feed',
        'description': 'falcon_feed',
        'typeVersion': '1.0',
        'attributeDefs': [{
          'name': 'frequency',
          'typeName': 'string',
          'isOptional': false,
          'cardinality': 'SINGLE',
          'valuesMinCount': 1,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }, {
          'name': 'stored-in',
          'typeName': 'falcon_cluster',
          'isOptional': false,
          'cardinality': 'SINGLE',
          'valuesMinCount': 1,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': true
        }, {
          'name': 'groups',
          'typeName': 'string',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }, {
          'name': 'tags',
          'typeName': 'map<string,string>',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }],
        'superTypes': ['DataSet']
      }, {
        'category': 'ENTITY',
        'guid': '9e4b6e42-4c96-4d1d-9983-222e2a6cc24b',
        'createTime': 1494492734290,
        'updateTime': 1494492734290,
        'version': 1,
        'name': 'hbase_table',
        'description': 'hbase_table',
        'typeVersion': '1.1',
        'attributeDefs': [{
          'name': 'uri',
          'typeName': 'string',
          'isOptional': false,
          'cardinality': 'SINGLE',
          'valuesMinCount': 1,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }, {
          'name': 'column_families',
          'typeName': 'array<hbase_column_family>',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false,
          'constraints': [{'type': 'ownedRef'}]
        }],
        'superTypes': ['DataSet']
      }, {
        'category': 'ENTITY',
        'guid': '75f59c4c-4b66-4ea8-8fc1-36131bbabfcb',
        'createTime': 1494492737114,
        'updateTime': 1494492737114,
        'version': 1,
        'name': 'storm_topology',
        'description': 'storm_topology',
        'typeVersion': '1.0',
        'attributeDefs': [{
          'name': 'id',
          'typeName': 'string',
          'isOptional': false,
          'cardinality': 'SINGLE',
          'valuesMinCount': 1,
          'valuesMaxCount': 1,
          'isUnique': true,
          'isIndexable': true
        }, {
          'name': 'startTime',
          'typeName': 'date',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }, {
          'name': 'endTime',
          'typeName': 'date',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }, {
          'name': 'conf',
          'typeName': 'map<string,string>',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }, {
          'name': 'clusterName',
          'typeName': 'string',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': true
        }, {
          'name': 'nodes',
          'typeName': 'array<storm_node>',
          'isOptional': false,
          'cardinality': 'LIST',
          'valuesMinCount': 1,
          'valuesMaxCount': 2147483647,
          'isUnique': false,
          'isIndexable': false
        }],
        'superTypes': ['Process']
      }, {
        'category': 'ENTITY',
        'guid': 'a525e59f-5ee9-4979-839f-3e73eba9ec91',
        'createTime': 1494492722460,
        'updateTime': 1494492722460,
        'version': 1,
        'name': 'Infrastructure',
        'description': 'Infrastructure',
        'typeVersion': '1.0',
        'attributeDefs': [],
        'superTypes': ['Referenceable', 'Asset']
      }, {
        'category': 'ENTITY',
        'guid': 'babbf867-7a2f-483a-a2df-b41ef07f1738',
        'createTime': 1494492737281,
        'updateTime': 1494492737281,
        'version': 1,
        'name': 'storm_spout',
        'description': 'storm_spout',
        'typeVersion': '1.0',
        'attributeDefs': [{
          'name': 'outputs',
          'typeName': 'array<string>',
          'isOptional': false,
          'cardinality': 'LIST',
          'valuesMinCount': 1,
          'valuesMaxCount': 2147483647,
          'isUnique': false,
          'isIndexable': false
        }],
        'superTypes': ['storm_node']
      }, {
        'category': 'ENTITY',
        'guid': '8d604e12-6d6e-425c-9fa4-9abab7443a66',
        'createTime': 1494492734325,
        'updateTime': 1494492734325,
        'version': 1,
        'name': 'hbase_column_family',
        'description': 'hbase_column_family',
        'typeVersion': '1.0',
        'attributeDefs': [{
          'name': 'table',
          'typeName': 'hbase_table',
          'isOptional': false,
          'cardinality': 'SINGLE',
          'valuesMinCount': 1,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false,
          'constraints': [{'type': 'inverseRef', 'params': {'attribute': 'column_families'}}]
        }, {
          'name': 'columns',
          'typeName': 'array<hbase_column>',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false,
          'constraints': [{'type': 'ownedRef'}]
        }],
        'superTypes': ['DataSet']
      }, {
        'category': 'ENTITY',
        'guid': '6923a9c7-69dd-44c9-8b77-c1698ba962dd',
        'createTime': 1494492720918,
        'updateTime': 1494492720918,
        'version': 1,
        'name': 'Asset',
        'description': 'Asset',
        'typeVersion': '1.0',
        'attributeDefs': [{
          'name': 'name',
          'typeName': 'string',
          'isOptional': false,
          'cardinality': 'SINGLE',
          'valuesMinCount': 1,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': true
        }, {
          'name': 'description',
          'typeName': 'string',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }, {
          'name': 'owner',
          'typeName': 'string',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': true
        }],
        'superTypes': []
      }, {
        'category': 'ENTITY',
        'guid': 'e66e6a03-c2ed-4bce-860c-c8db773c5f97',
        'createTime': 1494492730692,
        'updateTime': 1494500350917,
        'version': 5,
        'name': 'hive_column',
        'description': 'hive_column',
        'typeVersion': '1.4',
        'options': {'schemaAttributes': '[\'name\', \'description\', \'owner\', \'type\', \'comment\', \'position\']'},
        'attributeDefs': [{
          'name': 'type',
          'typeName': 'string',
          'isOptional': false,
          'cardinality': 'SINGLE',
          'valuesMinCount': 1,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': true
        }, {
          'name': 'comment',
          'typeName': 'string',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }, {
          'name': 'position',
          'typeName': 'int',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }, {
          'name': 'table',
          'typeName': 'hive_table',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }, {
          'name': 'profileData',
          'typeName': 'hive_column_profile_data',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }],
        'superTypes': ['DataSet']
      }, {
        'category': 'ENTITY',
        'guid': '7bc1ad4c-f8b9-42fc-82fb-e7cf72cd43c5',
        'createTime': 1494492735138,
        'updateTime': 1494492735138,
        'version': 1,
        'name': 'kafka_topic',
        'description': 'kafka_topic',
        'typeVersion': '1.0',
        'attributeDefs': [{
          'name': 'topic',
          'typeName': 'string',
          'isOptional': false,
          'cardinality': 'SINGLE',
          'valuesMinCount': 1,
          'valuesMaxCount': 1,
          'isUnique': true,
          'isIndexable': true
        }, {
          'name': 'uri',
          'typeName': 'string',
          'isOptional': false,
          'cardinality': 'SINGLE',
          'valuesMinCount': 1,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }],
        'superTypes': ['DataSet']
      }, {
        'category': 'ENTITY',
        'guid': 'e4fd516c-8b6f-4140-9dcf-a0a4dfe87192',
        'createTime': 1494492730458,
        'updateTime': 1494492730458,
        'version': 1,
        'name': 'hive_storagedesc',
        'description': 'hive_storagedesc',
        'typeVersion': '1.0',
        'attributeDefs': [{
          'name': 'table',
          'typeName': 'hive_table',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false,
          'constraints': [{'type': 'inverseRef', 'params': {'attribute': 'sd'}}]
        }, {
          'name': 'location',
          'typeName': 'string',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }, {
          'name': 'inputFormat',
          'typeName': 'string',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }, {
          'name': 'outputFormat',
          'typeName': 'string',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }, {
          'name': 'compressed',
          'typeName': 'boolean',
          'isOptional': false,
          'cardinality': 'SINGLE',
          'valuesMinCount': 1,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }, {
          'name': 'numBuckets',
          'typeName': 'int',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }, {
          'name': 'serdeInfo',
          'typeName': 'hive_serde',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }, {
          'name': 'bucketCols',
          'typeName': 'array<string>',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }, {
          'name': 'sortCols',
          'typeName': 'array<hive_order>',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }, {
          'name': 'parameters',
          'typeName': 'map<string,string>',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }, {
          'name': 'storedAsSubDirectories',
          'typeName': 'boolean',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }],
        'superTypes': ['Referenceable']
      }, {
        'category': 'ENTITY',
        'guid': 'd9f6a7ca-e092-4d5f-88ad-9d403ad9d1af',
        'createTime': 1494492727557,
        'updateTime': 1494492727557,
        'version': 1,
        'name': 'hdfs_path',
        'description': 'hdfs_path',
        'typeVersion': '1.0',
        'attributeDefs': [{
          'name': 'clusterName',
          'typeName': 'string',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': true
        }, {
          'name': 'numberOfReplicas',
          'typeName': 'int',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': true
        }, {
          'name': 'extendedAttributes',
          'typeName': 'map<string,string>',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }],
        'superTypes': ['fs_path']
      }, {
        'category': 'ENTITY',
        'guid': '5fa8e899-695f-442e-81a7-49e47fe2cde7',
        'createTime': 1494492732636,
        'updateTime': 1494492732636,
        'version': 1,
        'name': 'sqoop_process',
        'description': 'sqoop_process',
        'typeVersion': '1.0',
        'attributeDefs': [{
          'name': 'operation',
          'typeName': 'string',
          'isOptional': false,
          'cardinality': 'SINGLE',
          'valuesMinCount': 1,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': true
        }, {
          'name': 'commandlineOpts',
          'typeName': 'map<string,string>',
          'isOptional': false,
          'cardinality': 'SINGLE',
          'valuesMinCount': 1,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }, {
          'name': 'startTime',
          'typeName': 'date',
          'isOptional': false,
          'cardinality': 'SINGLE',
          'valuesMinCount': 1,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }, {
          'name': 'endTime',
          'typeName': 'date',
          'isOptional': false,
          'cardinality': 'SINGLE',
          'valuesMinCount': 1,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }, {
          'name': 'userName',
          'typeName': 'string',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': true
        }],
        'superTypes': ['Process']
      }, {
        'category': 'ENTITY',
        'guid': '635e9ab8-4254-463e-8a01-dfbb4402f462',
        'createTime': 1494492730740,
        'updateTime': 1494492730740,
        'version': 1,
        'name': 'hive_column_lineage',
        'description': 'hive_column_lineage',
        'typeVersion': '1.0',
        'attributeDefs': [{
          'name': 'query',
          'typeName': 'hive_process',
          'isOptional': false,
          'cardinality': 'SINGLE',
          'valuesMinCount': 1,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }, {
          'name': 'depenendencyType',
          'typeName': 'string',
          'isOptional': false,
          'cardinality': 'SINGLE',
          'valuesMinCount': 1,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }, {
          'name': 'expression',
          'typeName': 'string',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }],
        'superTypes': ['Process']
      }, {
        'category': 'ENTITY',
        'guid': '2ef623d9-3f12-459e-bdf8-dc411e517339',
        'createTime': 1494492737327,
        'updateTime': 1494492737327,
        'version': 1,
        'name': 'storm_bolt',
        'description': 'storm_bolt',
        'typeVersion': '1.0',
        'attributeDefs': [{
          'name': 'inputs',
          'typeName': 'array<string>',
          'isOptional': false,
          'cardinality': 'LIST',
          'valuesMinCount': 1,
          'valuesMaxCount': 2147483647,
          'isUnique': false,
          'isIndexable': false
        }, {
          'name': 'outputs',
          'typeName': 'array<string>',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }],
        'superTypes': ['storm_node']
      }, {
        'category': 'ENTITY',
        'guid': '9a24bbb6-3646-4924-b0d1-f6ecc2f6551a',
        'createTime': 1494492733350,
        'updateTime': 1494492733350,
        'version': 1,
        'name': 'falcon_cluster',
        'description': 'falcon_cluster',
        'typeVersion': '1.0',
        'attributeDefs': [{
          'name': 'colo',
          'typeName': 'string',
          'isOptional': false,
          'cardinality': 'SINGLE',
          'valuesMinCount': 1,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': true
        }, {
          'name': 'tags',
          'typeName': 'map<string,string>',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }],
        'superTypes': ['Infrastructure']
      }, {
        'category': 'ENTITY',
        'guid': '941c961a-ed49-4120-888b-3af507f4b2b0',
        'createTime': 1494492727435,
        'updateTime': 1494492727435,
        'version': 1,
        'name': 'fs_path',
        'description': 'fs_path',
        'typeVersion': '1.0',
        'attributeDefs': [{
          'name': 'path',
          'typeName': 'string',
          'isOptional': false,
          'cardinality': 'SINGLE',
          'valuesMinCount': 1,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': true
        }, {
          'name': 'createTime',
          'typeName': 'date',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': true
        }, {
          'name': 'modifiedTime',
          'typeName': 'date',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': true
        }, {
          'name': 'isFile',
          'typeName': 'boolean',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': true
        }, {
          'name': 'isSymlink',
          'typeName': 'boolean',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }, {
          'name': 'fileSize',
          'typeName': 'long',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': false
        }, {
          'name': 'group',
          'typeName': 'string',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': true
        }, {
          'name': 'posixPermissions',
          'typeName': 'fs_permissions',
          'isOptional': true,
          'cardinality': 'SINGLE',
          'valuesMinCount': 0,
          'valuesMaxCount': 1,
          'isUnique': false,
          'isIndexable': true
        }],
        'superTypes': ['DataSet']
      }]
    };
  }
}