---
swagger: '2.0'
info:
  title: Comments API for db-service
  version: 0.0.1
  description: |
    Proposed API for comments which will be used by other services to add/retrieve/update/delete comments

consumes:
  - application/json
produces:
  - application/json

paths:
  /{objectType}/{objectId}/comments:
    get:
      summary: Get a list of comments related to a particular object( e.g. a particular asset collection)
      parameters:
      - name: objectId
        in: path
        description: the ID of the object for which comments are fetched
        required: true
        type: string
      - name: objectType
        in: path
        description: the type of the object (e.g. assetCollection)
        required: true
        type: string

      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/CommentWithUser'
        404:
          description: entity not found
          schema:
            type: array
            items:
              $ref: '#/definitions/Error'
        500:
          description: internal server error
          schema:
            type: array
            items:
              $ref: '#/definitions/Error'

  /comments:
    post:
      summary: Add a new comment
      parameters:
        - in: body
          name: Comment
          required: true
          schema:
            $ref: '#/definitions/Comment'
      responses:
        201:
          description: CREATED
          schema:
            $ref: '#/definitions/CommentWithUser'
        400:
          description: request was malformed
        409:
          description: conflict while adding the comment
        500:
          description: internal server error
          schema:
            type: array
            items:
              $ref: '#/definitions/Error'


  /comments/{id}:
    patch:
      summary: Update the comment
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - name: commentText
          in: body
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/CommentWithUser'
        204:
          description: No content
        400:
          description: request was malformed
        500:
          description: internal server error
          schema:
            type: array
            items:
              $ref: '#/definitions/Error'

    delete:
      summary: Delete the specified comment
      parameters:
        - in: path
          name: id
          required: true
          type: string
      responses:
        200:
          description: OK
          schema:
            type: string
            description: Success message
        500:
          description: internal server error
          schema:
            type: array
            items:
              $ref: '#/definitions/Error'

definitions:

  Comment:
    description: Comment object which contains all information related to a comment
    type: object
    required:
      - objectType
      - objectId
      - createdBy
    properties:
      id:
        type: integer
        format: integer64
        description: id of the comment
      comment:
        type: string
        description: comment text
      objectType:
        type: string
      objectId:
        type: integer
        format: integer64
      createdBy:
        type: integer
        format: integer64
      createdOn:
        type: string
        format: date-time
      lastModified:
        type: string
        format: date-time
      parentCommentId:
        type: integer
        format: integer64
      editVersion:
        type: integer
        format: integer32

  CommentWithUser:
    description: Comment object along with user name
    type: object
    required:
      - comment
      - userName
    properties:
      comment:
        $ref: '#/definitions/Comment'
      userName:
        type: string

  Error:
    type: object
    required:
      - code
      - message
      - errorType
    properties:
      code:
        type: string
        description: Error code
      message:
        type: string
        description: Description/trace of the error
      errorType:
        type: string
        description: Text describing the type of errror , may be indicating its origin