version: '2'
services:
  dp-database:
    image: postgres
    environment:
        POSTGRES_PASSWORD: dp_admin
        POSTGRES_USER: dp_admin
        POSTGRES_DB: dataplane
  dp-db-service:
    build:
        context: ../services/db-service
    image: hortonworks/dp-db-service
    ports:
        - "9000:9000"
    depends_on:
        - dp-database
    links:
        - dp-database
  dp-app:
    build:
        context: .
    image: hortonworks/dp-app
    ports:
        - "80:80"
    depends_on:
        - dp-db-service
        - dp-database
    links:
        - dp-db-service
        - dp-database
  dp-cluster-service:
    build:
        context: ../services/cluster-service
    image: hortonworks/dp-cluster-service
    depends_on:
        - dp-database
    links:
        - dp-database
