#!/bin/sh
if [ -z "$CONSUL_HOST" ]; then
    echo "Need to set CONSUL_HOST"
    exit 1
fi
exec 2>&1
rm -f /usr/dss-app/RUNNING_PID && \
cd /usr/dss-app/bin && \
exec ./dss-app -DDSS_APP_HOME=${DSS_APP_HOME} \
               -Dconfig.resource=../conf/docker.conf \
               -Dplay.crypto.secret="129921029813" \
               -Dconsul.host=${CONSUL_HOST}
