apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ template "projectName" . }}
    version: {{ .Chart.Version }}
    dpVersion: {{ .Values.global.dpVersion }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgres.user | b64enc | quote}}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | default (randAlphaNum 32) | b64enc | quote }}