#
# A Deployment spec for consul. Unlike the stable/consul helm chart, this
# one is pretty simple since we will only have a single node consul per
# DP instance, and no PV support yet.
#
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name:  {{ .Values.app.name }}-{{.Release.Name}}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.app.name }}
    version: {{ .Chart.Version }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
      release: {{ .Release.Name }}
      type: deployment-pod
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        release: {{ .Release.Name }}
        type: deployment-pod
    spec:
      containers:
        - name: consul
          image: {{ .Values.image.name }}:{{ .Values.image.version }}
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          args:
              # https://www.consul.io/docs/agent/options.html
              - "agent"
              - "-server"
              - "-ui"
              - "-bootstrap"
              - "-bind=0.0.0.0"
              - "-client=0.0.0.0"
              - "-data-dir={{ .Values.dataDir }}"
              - "-disable-host-node-id"
          ports:
              - containerPort: 8500
                name: ui-port
              - containerPort: 8400
                name: alt-port
              - containerPort: 53
                name: udp-port
              - containerPort: 8443
                name: https-port
              - containerPort: 8080
                name: http-port
              - containerPort: 8301
                name: serflan
              - containerPort: 8302
                name: serfwan
              - containerPort: 8600
                name: consuldns
              - containerPort: 8300
                name: server
          volumeMounts:
            - mountPath: {{ .Values.mountDir }}
              name: consul-volume
      volumes:
        - name: consul-volume
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (printf "consul-pvc-%s" .Release.Name) }}
        {{- else }}
          emptyDir: {}
        {{- end }}